/* Generated By:JavaCC: Do not edit this line. MainConstants.java */
package calculator;

public interface MainConstants {

  int EOF = 0;
  int NUMBER = 3;
  int DIGIT = 4;
  int SUB = 5;
  int ADD = 6;
  int MULT = 7;
  int DIV = 8;
  int LET = 9;
  int VARIABLE = 10;
  int LETTER = 11;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<NUMBER>",
    "<DIGIT>",
    "\"sub\"",
    "\"add\"",
    "\"mult\"",
    "\"div\"",
    "\"let\"",
    "<VARIABLE>",
    "<LETTER>",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
